pipefail and set -e in screen_capture

diff --git a/var/lib/lernstick-exam-client/persistent/usr/bin/screen_capture b/var/lib/lernstick-exam-client/persistent/usr/bin/screen_capture
--- a/var/lib/lernstick-exam-client/persistent/usr/bin/screen_capture
+++ b/var/lib/lernstick-exam-client/persistent/usr/bin/screen_capture
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# commands which fail will cause the shell script to exit immediately
+set -eo pipefail
+
 . /var/lib/lernstick-exam-client/functions.sh
 
 c="$(config_value "screen_capture_chunk")"
@@ -20,23 +23,19 @@ path="${c:-"/home/user/ScreenCapture"}"
 command="$(config_value "screen_capture_command")"
 output="${path}/video.m3u8"
 
-while true; do
-  # get DISPLAY and XAUTHORITY env vars
-  set -o allexport
-  . <(strings /proc/*/environ 2>/dev/null | awk -F= '$1=="DISPLAY"||$1=="XAUTHORITY"' | head -2) 
-  set +o allexport
+# get DISPLAY and XAUTHORITY env vars
+set -o allexport
+. <(strings /proc/*/environ 2>/dev/null | awk -F= '$1=="DISPLAY"||$1=="XAUTHORITY"' | head -2) 
+set +o allexport
 
-  resolution="$(xdpyinfo | awk '$1=="dimensions:"{print $2}')"
-  gop="$(bc <<< "${chunk}*${fps}")"
-  mkdir -p "${path}"
-  cd "${path}"
-  date="$(date +%s)"
-  master="master${date}.m3u8"
-  playlist="video${date}.m3u8"
+resolution="$(xdpyinfo | awk '$1=="dimensions:"{print $2}')"
+gop="$(bc <<< "${chunk}*${fps}")"
+mkdir -p "${path}"
+cd "${path}"
+date="$(date +%s)"
+master="master${date}.m3u8"
+playlist="video${date}.m3u8"
 
-  echo "[screen_capture] [info] Starting screen capturing..."
-  echo "[screen_capture] [info] calling ${command}"
-  eval "${command}"
-  sleep 10 # retry after 10 seconds
-done
-
+echo "[screen_capture] [info] Starting screen capturing..."
+echo "[screen_capture] [info] calling ${command}"
+eval "${command}"
