version check looking at grub config string to distinguish exam/non-exa

diff --git a/usr/bin/searchExamServer b/usr/bin/searchExamServer
--- a/usr/bin/searchExamServer
+++ b/usr/bin/searchExamServer
@@ -345,6 +345,12 @@ fi
 # get server information
 client_version="$(cat "$compatFile" | ${python} -c 'import sys, json; print json.load(sys.stdin)["client_version"]')"
 lernstick_version="$(grep -ohP '[0-9,\-]{8,}' /run/live/rootfs/filesystem.squashfs/usr/local/lernstick.html /usr/local/lernstick.html 2>/dev/null | sed 's/-//g' | head -1)"
+if [ -r "/run/live/medium/boot/grub/themes/lernstick/theme.txt" ]; then
+  lernstick_flavor="$(grep -qP "title-text.*Prüfung" /run/live/medium/boot/grub/themes/lernstick/theme.txt 2>/dev/null && echo exam || echo standard)"
+else
+  lernstick_flavor="exam" # fallback to exam if the file does not exist
+fi
+
 wants_server_version="$(cat "$compatFile" | ${python} -c 'import sys, json; print json.load(sys.stdin)["wants_server_version"]')"
 jsonInfo="$(${wget} ${wgetOptions} -qO- "${actionInfo}")"
 
@@ -355,6 +361,7 @@ if [ ${retval} -eq 0 ]; then
   server_version="$(echo "$jsonInfo" | ${python} -c 'import sys, json; print json.load(sys.stdin)["server_version"]')"
   wants_client_version="$(echo "$jsonInfo" | ${python} -c 'import sys, json; print json.load(sys.stdin)["wants_client_version"]')"
   wants_lernstick_version="$(echo "$jsonInfo" | ${python} -c 'import sys, json; print json.load(sys.stdin)["wants_lernstick_version"]')"
+  wants_lernstick_flavor="$(echo "$jsonInfo" | ${python} -c 'import sys, json; print json.load(sys.stdin)["wants_lernstick_flavor"]')"
   >&2 echo "client_version = $client_version"
   >&2 echo "wants_server_version = $wants_server_version"
   >&2 echo "server_version = $server_version"
@@ -363,6 +370,11 @@ if [ ${retval} -eq 0 ]; then
     >&2 echo "Server version mismatch. Got ${server_version}, but client needs ${wants_server_version}."
     ${zenity} --error --width=300 --title "$(gettext "Version Error")" --text "$(eval_gettext "Server version mismatch. Got \${server_version}, but client needs \${wants_server_version}.")"
     do_exit "Server version mismatch. Got ${server_version}, but client needs ${wants_server_version}."
+  fi
+  if ! [ "$lernstick_flavor" = "$wants_lernstick_flavor" ]; then
+    >&2 echo "Lernstick version mismatch. Got ${lernstick_flavor}, but server needs ${wants_lernstick_flavor}."
+    ${zenity} --error --width=300 --title "$(gettext "Version Error")" --text "$(eval_gettext "Lernstick version mismatch. Got \${lernstick_flavor}, but server needs \${wants_lernstick_flavor}. Please use the Lernstick exam environment instead of the standard environment. You can find the Lernstick exam environment under the following URL: https://www.digitale-nachhaltigkeit.unibe.ch/dienstleistungen/lernstick/downloads")"
+    do_exit "Lernstick version mismatch. Got ${lernstick_flavor}, but server needs ${wants_lernstick_flavor}."
   fi
   if ! check_version "$lernstick_version" "$wants_lernstick_version"; then
     >&2 echo "Lernstick version mismatch. Got ${lernstick_version}, but server needs ${wants_lernstick_version}."
